MKSHELL="/bin/bash"

# Extract FASTA consensus sequences from bed data
%.mirmut:Q: %.fa.consensus
	bed=$(find -L . -type f -name "*.bed")
	echo "[DEBUG] Processing bed: $bed"
	tail -n +2 $bed | cut -f 1-6  > $bed.tmp
	echo "[DEBUG] Extracting $prereq into $target"
	bedtools getfasta -fi $prereq -bed $bed.tmp -name -s -fo $stem.tmp
	echo "[DEBUG] Change DNA to RNA"
	less -s $stem.tmp | tr "T" "U" > $target
