MKSHELL=/bin/bash

%.SPLITVCF:Q: %.vcf.gz
	echo "[DEBUF] indexing $prereq"
	bcftools index $prereq
	echo "[DEBUG] splitting by chromosome the following vcf: $prereq"
	for chromosome in $(tabix --list-chroms $prereq)
	do
		subtarget="$stem.chunk$chromosome.vcf"
		echo "[>..] Extracting $chromosome into $subtarget"
		bcftools view $prereq $chromosome > $subtarget
	done
