MKSHELL="/bin/bash"
#Find input files and pass to TargetScan script
%.tsout:Q: %.mirna.txt
	echo "[DEBUG] searching input files"
	utr_fasta=$(find -L . -type f -name "*.utr.txt")
	echo "[DEBUG] $prereq"
	perl targetscan_70.pl $prereq $utr_fasta $target
