MKSHELL="/bin/bash"

# make consensus sequence
%.fa.consensus:Q: %.vcf.gz.tmp
	fastas=$(find -L . -type f -name "*.fa")
	for fasta in $fastas
	do
		fasta_chrom=$(grep ">" $fasta | tr -d ">")
		vcf_chrom=$(bcftools query -f '%CHROM\n' $prereq | head -1)
		if [ $fasta_chrom == $vcf_chrom ]
		then
		echo "[DEBUG] Creando secuencia consenso de $fasta a partir de $prereq"
		cat $fasta | bcftools consensus $prereq > $target
		fi
	done && rm $prereq && rm $prereq.csi

# filter and index vcf file
%.vcf.gz.tmp:Q: %.vcf.gz
	echo "[DEBUG] filtering $prereq"
	bcftools norm -m+ $prereq | bcftools view -m2 -M2 -v snps |	bgzip -c > $target
	echo "[DEBUG] indexing $prereq"
	bcftools index $target
